ALTER TABLE subscriptions
    ADD COLUMN start_date timestamp with time zone NOT NULL DEFAULT now();

ALTER TABLE subscriptions
    ADD COLUMN last_updated timestamp with time zone NULL;

CREATE TABLE subscription_episodes
(
    id              int8        NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    subscription_id int8        NOT NULL,
    episode_id      varchar(32) NOT NULL,
    CONSTRAINT subscription_episodes_pkey PRIMARY KEY (id)
);